### model
model_name_or_path: /root/model/Qwen3-8B
adapter_name_or_path: /root/train_output/Qwen3-8B-LoRA-BPA-0813
finetuning_type: lora
template: qwen3_nothink

### export
export_dir: /root/merge_result/Qwen3-8B-LoRA-BPA-0813
export_size: 5
export_device: cpu
export_legacy_format: false
